// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApr88P0hmZK2FmK3Adu-cd8siUzYTIQjE',
    appId: '1:675412789332:web:9d76057c62a57a1f78c5c1',
    messagingSenderId: '675412789332',
    projectId: 'doctor-appointment-app-71d3c',
    authDomain: 'doctor-appointment-app-71d3c.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-71d3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzcDvIZO7SYQFLqvMAfiUBlfPvEEprcgM',
    appId: '1:675412789332:android:dee864e888e97b6f78c5c1',
    messagingSenderId: '675412789332',
    projectId: 'doctor-appointment-app-71d3c',
    storageBucket: 'doctor-appointment-app-71d3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOpp1CpF2O7BoMijPEUVT1fbDL6pKbfO8',
    appId: '1:675412789332:ios:f69a60bb15a6dda278c5c1',
    messagingSenderId: '675412789332',
    projectId: 'doctor-appointment-app-71d3c',
    storageBucket: 'doctor-appointment-app-71d3c.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );
}
